export enum TransactionTypes {
  USER_WALLET_TRANSACTION_TYPE_UNKNOWN = 0,
  USER_WALLET_TRANSACTION_TYPE_WITHDRAW = 1,
  USER_WALLET_TRANSACTION_TYPE_DEPOSIT = 2,
  USER_WALLET_TRANSACTION_TYPE_TRANSFER = 3,
  USER_WALLET_TRANSACTION_TYPE_COMMISSION_DIRECT = 4,
  USER_WALLET_TRANSACTION_TYPE_COMMISSION_MATRIX = 5,
  USER_WALLET_TRANSACTION_TYPE_COMMISSION_GLOBAL_SHARE = 6,
  USER_WALLET_TRANSACTION_TYPE_REFUND = 7,
  USER_WALLET_TRANSACTION_TYPE_SYSTEM_ADD = 8,
  USER_WALLET_TRANSACTION_TYPE_SYSTEM_SUBTRACT = 9,
  USER_WALLET_TRANSACTION_TYPE_MAKE_UP_BALANCE = 10,
  USER_WALLET_TRANSACTION_TYPE_TRANSFER_LIFE_POINT_TO_USDT = 11,
}

export enum TransactionStatus {
  USER_WALLET_TRANSACTION_STATUS_CREATED= 1,
  USER_WALLET_TRANSACTION_STATUS_SUCCESS= 2,
  USER_WALLET_TRANSACTION_STATUS_FAILED= 3,
};


export enum ConfirmWalletTypes {
  SETTINGS = 1,
  WITHDRAW = 2,
}

export const autoLockMethod = {
  minute1: 60,
  minutes5: 300,
  hour1: 3600,
  hour5: 18000,
  always: -1,
};

export const TokenCodes = {
  USDT: 'USDT',
  LIFE: 'LP',
};

